### ISSUE TITLE
Failing to instal using ember-cli v0.2.3 'ember install ember-material-design'

### ISSUE THREAD

**Issue by opichals** [mike1o1/ember-material-design#10]
The addon install is failing with the following output. Even on a freshly created ember-cli application.

```
./node_modules/.bin/ember install ember-material-design
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Installed packages for tooling via npm.
installing
  identical app/styles/app.scss
installing
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.
```

```
./node_modules/.bin/ember --version
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
node: 0.12.2
npm: 2.7.6
```

**Comment by mike1o1** [comment]
Hi, thanks for the feedback. I did some investigating and it looks like this might be an issue with Ember CLI 0.2.3 and not with the addon. I did some tests, an the addon is still installing correctly, but Ember CLI is still silently throwing the error. 

See https://github.com/ember-cli/ember-cli/issues/3831 for more information.

Closing for now as the addon still installs and works correctly. I'll reopen if further Ember CLI upgrades require some changes.
