### ISSUE TITLE
core/typography.css URI is missing ')'

### ISSUE THREAD

**Issue by yanzixiang** [mike1o1/ember-material-design#12]
using ember-cli v0.2.3

ember install ember-material-design
ember install ember-cli-sass
ember install ember-cli-autoprefixer
ember serve

 i got this error

**Comment by mike1o1** [comment]
Thanks for the feedback. I believe this is an issue with the current beta of node-sass, which is what gets installed with current versions of `ember-cli-sass` right now. I'd suggest sticking with an earlier version until this issue gets resolved.

I personally use `ember-cli-sass@3.1.0`. Or if you specify a working version of `node-sass` as suggested in https://github.com/aexmachina/ember-cli-sass/issues/40 then that should solve this problem.
