### ISSUE TITLE
Use <progress> Element for md-progress

### ISSUE THREAD

**Issue by srsgores** [mike1o1/ember-material-design#14]
All that is needed is to set ``tagName`` to progress, adding ``min``, and ``max`` attributes to take advantage of the HTML5 ``<progress>`` element [here](https://github.com/mike1o1/ember-material-design/blob/master/addon/components/md-progress-linear.js).

PR to come shortly.

**Comment by srsgores** [comment]
Furthermore, it makes no sense to have to set ``mode`` to ``indeterminate``; instead, we should emulate the HTML5 ``progress`` behaviour, which is to default to ``indeterminate``.

I will demonstrate in the PR.

**Comment by mike1o1** [comment]
Thanks for the feedback, but I'm not sure I see the value in this. The purpose was to avoid clobbering the native element.
