### ISSUE TITLE
md-button action args?

### ISSUE THREAD

**Issue by yanzixiang** [mike1o1/ember-material-design#30]
how to pass an action args from the md-button to the controller?

{{#md-button class="md-raised md-primary" action='gotoModels' brand.BrandName}}

does not work !

**Comment by DrCorduroy** [comment]
Use the "param" attribute.

{{#md-button class="md-raised md-primary" action='gotoModels' param=brand.BrandName}}

The md-button passes the attribute "param" in it's sendAction implementation. https://github.com/mike1o1/ember-material-design/blob/ac7dcdfa92587fe163b456e432f13ecd0261cb96/addon/components/md-button.js
