### ISSUE TITLE
Reopen input helpers and add support for md attributes?

### ISSUE THREAD

**Issue by jhr007** [mike1o1/ember-material-design#31]
I was trying to add "layout-fill" to a textarea, but it didn't get past the textarea helper. 

Then I found that I need to reopen the Helper class and add acceptable attributes. 
http://stackoverflow.com/questions/18189614/adding-attributes-to-input-element-in-handlebars-used-with-ember-js
and I should do this in initializers:
http://stackoverflow.com/questions/27154886/ember-cli-where-to-reopen-framework-classes

Maybe some attributes could be added to helpers by ember-material-design?
https://material.angularjs.org/latest/#/layout/options
`layout-fill` I could make the argument for this on input fields to maximize width in a container.
Maybe `flex` ? to normalize fields? 

Has anyone else had to reopen input helpers to get Material Design attributes in the helper?

**Comment by mike1o1** [comment]
I didn't think about adding this to input helpers. I'm already doing this for Views and LinkViews, so I'll add for input helpers in the future. For now, you can always just create your own initializer. Follow [app/initializers/md-layout-views.js](https://github.com/mike1o1/ember-material-design/blob/a233f645b37ab90ae808002b7977a89f6ea1d898/app/initializers/md-layout-views.js) as an example.

**Comment by jhr007** [comment]
Thanks for the info.

I wasn't sure if this was just me or if others also have a need.

**Comment by mike1o1** [comment]
Now that I think about it, a better option is that you should be adding these attributes to the md-input-container, not necessarily to the md-input component. 

```hbs
<div layout="row" layout-align="start space-between">
  {{#md-input-container value=model.name flex=''}}
      <label for="">Name</label>
    {{md-input type="text"}}
  {{/md-input-container}}

  {{#md-input-container value=model.description md-no-float='' flex='33'}}
      <label for="">Description</label>
    {{md-textarea columns="1"}}
  {{/md-input-container}}
</div>
```

Let me know if that doesn't work out for you. Thanks!

**Comment by jhr007** [comment]
Thanks I'll look into it
