### ISSUE TITLE
Trying to understand the Grid

### ISSUE THREAD

**Issue by hhff** [mike1o1/ember-material-design#32]
Hi @mike1o1 !

Loving this man! amazing how quick it was for me to get up and going.  Congrats on the great work!!

I'm looking to understand how I can do something like:

```html
<div class="row">
  <div class="col-xs-12
              col-sm-8
              col-md-6
              col-lg-4">
  </div>
</div>
```

Basically, how can I set the width of an element (say, an `md-card`) based on the current breakpoint?

**Comment by DrCorduroy** [comment]
As this is a port from material-angular just take a look at their docs: 
https://material.angularjs.org/latest/#/layout/grid

**Comment by hhff** [comment]
Oh nice!!!!  You're the man!!
