### ISSUE TITLE
Document/Examples of {{md-sidenav}}

### ISSUE THREAD

**Issue by jhr007** [mike1o1/ember-material-design#33]
I found there is an md-sidenav as a component but it's documented on: http://mike1234.com/ember-material-design/#/buttons

**Comment by peec** [comment]
There are many examples inside the dummy app:
md-sidenav specifically in application.hbs:

https://github.com/mike1o1/ember-material-design/blob/master/tests/dummy/app/templates/application.hbs

**Comment by mike1o1** [comment]
As peec mentioned, the main dummy app has a sidenav you can use as an example. I'll add a demo page eventually.

Also, be sure to hook into the `didTransition` event to hide the navbar on transition.

``` js
import Ember from 'ember';

var ApplicationRoute = Ember.Route.extend({
  actions: {
    didTransition: function() {
      this.controller.set('sidebarVisible', false);
    }
  }
});

export default ApplicationRoute;
```
