### ISSUE TITLE
Grid and Animations

### ISSUE THREAD

**Issue by thiagoc7** [mike1o1/ember-material-design#7]
Hi, thanks for this amazing addon!

I´m using `materialize` until now, but I agree that a native ember solution is much better.

Are you going to have a `grid` system? If not, do you recoment any external grid framework?

About animations, it seems that `liquid-fire` is the official choice from Ember core team, and I agree that it´s fantastic.
But it allways break css, and it happend with materialize.
Do you like the idea of having native support for `liquid-fire`? In a way that we can use it with `ember-md` and don´t have to worry about it, just works as it should.

I´m building a skeleton app for my next projects, based on `rails + ember + materialize`.
My idea is to have a dashboard theme, using many addons that I like, all tested and working from server to frontend.
This way would be much faster to start a new app, and I think it could help people to start with ember.
It is very early WIP, and I couldn´t work on this on the past weeks, but I´ll came back next week.
And I´ll change the dependecies pro materialize to your addon, here is the [repo](https://github.com/thiagoc7/base_app).

Cheers!

**Comment by mike1o1** [comment]
Thanks for the kind words! There is indeed a layout/grid system, though it isn't documented yet. I'll add a page tonight showing how to use it and show some examples.

I haven't looked into `liquid-fire` much beyond the last demo at Ember Conf, but I'd prefer to try and stick with class based animations as much as I can.

**Comment by thiagoc7** [comment]
thanks for the feedback!
Sorry for my poor english, I don't mean to include `liquid-fire` in your addon.
I just mean to support nested divs without breaking the design.

But I created a `test-app`, and your code seems to work great with `liquid-fire`.

Thanks again!
