### ISSUE TITLE
sass should be a dependency on package.json

### ISSUE THREAD

**Issue by thiagoc7** [mike1o1/ember-material-design#9]
or you need to provide css files.

**Comment by mike1o1** [comment]
I'd prefer not to have it as a dependency, as I've seen `broccoli-sass` and `ember-cli-sass` have about equal usage in some sample apps I've seen, and it should be up to the consumer of the addon to decide which compiler they'd like to use. I've updated the readme to mention this.

I've also updated the readme to mention that an autoprefixer should be used, as none of the stylesheets currently have vendor prefixes. Again, I believe this is something the consuming application should handle, not the addon.
